/**
 * AdSense slot IDs — single source of truth.
 *
 * Each constant below maps to an ad unit you create in the AdSense dashboard
 * (https://adsense.google.com → Ads → By ad unit → Create). Until you create
 * them, the placeholder strings render as empty ad units (no impressions, no
 * errors). Replace each placeholder with the slot ID returned by the dashboard.
 *
 * Why split by placement instead of one global slot?
 *   - Per-placement performance tracking in AdSense (CTR, RPM by location)
 *   - Different ad formats need different unit types (display vs in-article
 *     vs in-feed vs anchor vs multiplex)
 *   - Lets you turn off individual placements without code changes
 */

export const ADSENSE_CLIENT_ID = "ca-pub-2908534121884582";

/** Display ad — horizontal banner below the global footer, every page. */
export const SLOT_FOOTER_BANNER = "3721773684";

/** Display ad rendered in a fixed mobile bottom bar. AdSense doesn't expose
 *  Anchor ads as a manual unit type (they're an Auto Ads format), so we use
 *  a regular Display unit and position it ourselves. */
export const SLOT_MOBILE_ANCHOR = "5474369280";

/** In-article horizontal — placed between content sections on building/landlord pages. */
export const SLOT_IN_CONTENT = "6619399769";

/** Vertical (300x600 skyscraper) — right sidebar on building page. */
export const SLOT_SIDEBAR_VERTICAL = "6787450959";

/** Vertical floating rail — static pages, fills empty space outside max-w container. */
export const SLOT_FLOATING_RAIL = "6480329193";

/** In-feed — between cards on listing pages (rankings, search, feed). */
export const SLOT_IN_FEED = "3854165858";

/** In-feed layout key generated by the AdSense dashboard at unit creation time.
 *  Required by AdSense's in-feed format — without it the ad reads as a generic
 *  display block. Regenerate via the dashboard if you restyle the unit. */
export const SLOT_IN_FEED_LAYOUT_KEY = "-fb+5w+4e-db+86";

/** Multiplex (related content grid) — bottom of article-style pages. */
export const SLOT_MULTIPLEX = "5540297988";

/**
 * Check if a slot is real (not a placeholder). Used to no-op renders before
 * the user has wired up AdSense, so we don't ship empty `<ins>` tags that
 * AdSense logs as "no fill" warnings.
 */
export function isRealSlot(slot: string): boolean {
  return !slot.startsWith("TODO_");
}
