import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

/**
 * Landlord sitemap index. Computes the chunk range from the live row
 * count in `landlord_stats` rather than reading `public/sitemap/`.
 *
 * Why not filesystem: a previous version called `readdir(process.cwd() +
 * "/public/sitemap")`, which caused Vercel's function bundler to inline
 * the entire 635 MB sitemap directory into the function bundle (exceeded
 * the 250 MB per-function limit). Computing the range from the DB keeps
 * this route a tiny pure function.
 *
 * The chunk files themselves are static assets in `public/sitemap/`,
 * generated by `scripts/generate-sitemaps.mjs` (10,000 URLs per file).
 * If row count and on-disk file count drift (e.g. between a regen and
 * a fresh DB sync), Google will get a 404 on the trailing chunk — fine,
 * just rerun the regen script.
 */

const BASE_URL = "https://lucidrents.com";
const URLS_PER_CHUNK = 10000;

export const revalidate = 86400; // 24h ISR

export async function GET() {
  try {
    const supabase = await createClient();
    const { count, error } = await supabase
      .from("landlord_stats")
      .select("*", { count: "exact", head: true })
      .gt("building_count", 0);

    if (error || count === null) {
      return new NextResponse("Error", { status: 500 });
    }

    const chunkCount = Math.ceil(count / URLS_PER_CHUNK);
    const now = new Date().toISOString();
    const blocks: string[] = [];
    for (let i = 0; i < chunkCount; i++) {
      blocks.push(
        `  <sitemap>\n    <loc>${BASE_URL}/sitemap/l-${i}.xml</loc>\n    <lastmod>${now}</lastmod>\n  </sitemap>`
      );
    }

    const body =
      '<?xml version="1.0" encoding="UTF-8"?>\n' +
      '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
      blocks.join("\n") +
      "\n</sitemapindex>\n";

    return new NextResponse(body, {
      headers: {
        "Content-Type": "application/xml",
        "Cache-Control":
          "public, s-maxage=86400, stale-while-revalidate=3600",
      },
    });
  } catch {
    return new NextResponse("Error", { status: 500 });
  }
}
