import { createClient } from "@supabase/supabase-js";
import { CITY_META, type City } from "@/lib/cities";
import { approveDraft, rejectDraft } from "./actions";
import PendingList, { type PendingDraft } from "./PendingList";

// Middleware enforces /mission-control/* auth; this page is unreachable
// without a valid mc_auth cookie.
export const dynamic = "force-dynamic";

interface Draft {
  id: string;
  metro: string;
  title: string;
  excerpt: string | null;
  body: string | null;
  category: string;
  image_url: string | null;
  signal_type: string | null;
  signal_metadata: Record<string, unknown> | null;
  created_at: string;
  status: string;
  published_at: string | null;
}

const TABS = ["pending", "approved", "rejected"] as const;
type Tab = (typeof TABS)[number];

function timeAgo(iso: string): string {
  const ms = Date.now() - new Date(iso).getTime();
  const m = Math.floor(ms / 60000);
  if (m < 60) return `${m}m ago`;
  const h = Math.floor(m / 60);
  if (h < 24) return `${h}h ago`;
  return `${Math.floor(h / 24)}d ago`;
}

async function countsByStatus(admin: ReturnType<typeof createClient<any>>): Promise<Record<Tab, number>> {
  const [pending, approved, rejected] = await Promise.all([
    admin.from("news_articles").select("id", { count: "exact", head: true }).eq("status", "draft").eq("auto_generated", true),
    admin.from("news_articles").select("id", { count: "exact", head: true }).eq("status", "published").eq("auto_generated", true),
    admin.from("news_articles").select("id", { count: "exact", head: true }).eq("status", "rejected").eq("auto_generated", true),
  ]);
  return {
    pending: pending.count ?? 0,
    approved: approved.count ?? 0,
    rejected: rejected.count ?? 0,
  };
}

export default async function NewsDraftsPage({
  searchParams,
}: {
  searchParams: Promise<{ tab?: string }>;
}) {
  const { tab } = await searchParams;
  const activeTab: Tab = TABS.includes(tab as Tab) ? (tab as Tab) : "pending";

  const dbStatus =
    activeTab === "pending" ? "draft" : activeTab === "approved" ? "published" : "rejected";
  const orderCol = activeTab === "approved" ? "published_at" : "created_at";

  const admin = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  );

  const [{ data: rowsRaw, error }, counts] = await Promise.all([
    admin
      .from("news_articles")
      .select(
        "id, metro, title, excerpt, body, category, image_url, signal_type, signal_metadata, created_at, status, published_at"
      )
      .eq("status", dbStatus)
      .eq("auto_generated", true)
      .order(orderCol, { ascending: false })
      .limit(100),
    countsByStatus(admin),
  ]);

  if (error) {
    return (
      <main className="max-w-2xl mx-auto p-8">
        <h1 className="text-2xl font-bold text-red-600">Error loading drafts</h1>
        <pre className="mt-4 text-sm bg-red-50 p-4 rounded">{error.message}</pre>
      </main>
    );
  }

  const rows = (rowsRaw ?? []) as Draft[];
  const byCity = new Map<string, Draft[]>();
  for (const r of rows) {
    const arr = byCity.get(r.metro) ?? [];
    arr.push(r);
    byCity.set(r.metro, arr);
  }

  return (
    <main className="max-w-5xl mx-auto p-8">
      <header className="mb-6 flex items-end justify-between gap-4 border-b border-[#e2e8f0] pb-4">
        <div>
          <p className="text-xs uppercase tracking-wider text-[#3B82F6] font-medium">
            Mission Control
          </p>
          <h1 className="text-3xl font-bold mt-1">News drafts</h1>
          <p className="text-sm text-[#64748b] mt-2">
            Auto-generated by the news cron. Approve to publish or reject.
          </p>
        </div>
        <div className="flex items-center gap-4">
          <span className="text-sm text-[#64748b]">
            {rows.length} {activeTab}
          </span>
          <form action="/api/mission-control/logout" method="post">
            <button
              type="submit"
              className="text-sm text-[#64748b] hover:text-[#0F1D2E] font-medium"
            >
              Log out
            </button>
          </form>
        </div>
      </header>

      <nav className="mb-6 flex gap-1 border-b border-[#e2e8f0]">
        {TABS.map((t) => {
          const active = t === activeTab;
          return (
            <a
              key={t}
              href={`/mission-control/news-drafts?tab=${t}`}
              className={`relative px-4 py-2 text-sm font-medium capitalize ${
                active
                  ? "text-[#3B82F6] border-b-2 border-[#3B82F6] -mb-px"
                  : "text-[#64748b] hover:text-[#0F1D2E]"
              }`}
            >
              {t}
              <span
                className={`ml-2 inline-flex items-center justify-center rounded-full px-1.5 py-0.5 text-xs ${
                  active
                    ? "bg-[#3B82F6]/10 text-[#3B82F6]"
                    : "bg-slate-100 text-[#64748b]"
                }`}
              >
                {counts[t]}
              </span>
            </a>
          );
        })}
      </nav>

      {rows.length === 0 ? (
        <p className="text-[#64748b] py-12 text-center border border-dashed border-[#e2e8f0] rounded-lg">
          {activeTab === "pending"
            ? "No drafts pending. The cron will produce new drafts overnight."
            : activeTab === "approved"
              ? "No approved articles yet."
              : "No rejected drafts."}
        </p>
      ) : activeTab === "pending" ? (
        <PendingList drafts={rows as PendingDraft[]} />
      ) : (
        Array.from(byCity.entries()).map(([cityKey, cityDrafts]) => {
          const cityName = CITY_META[cityKey as City]?.name ?? cityKey;
          return (
            <section key={cityKey} className="mb-10">
              <h2 className="text-lg font-semibold text-[#0F1D2E] mb-3 flex items-center gap-2">
                {cityName}
                <span className="text-xs font-normal text-[#64748b]">
                  ({cityDrafts.length})
                </span>
              </h2>
              <div className="space-y-4">
                {cityDrafts.map((d) => (
                  <DraftCard key={d.id} draft={d} tab={activeTab} />
                ))}
              </div>
            </section>
          );
        })
      )}
    </main>
  );
}

function DraftCard({ draft, tab }: { draft: Draft; tab: Tab }) {
  const approve = approveDraft.bind(null, draft.id);
  const reject = rejectDraft.bind(null, draft.id);

  return (
    <article className="border border-[#e2e8f0] rounded-xl overflow-hidden bg-white">
      {draft.image_url && (
        <div className="relative h-48 w-full bg-[#f1f5f9]">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={draft.image_url}
            alt=""
            className="h-full w-full object-cover"
          />
        </div>
      )}
      <div className="p-5">
        <div className="flex items-center gap-2 text-xs text-[#64748b] mb-3">
          <span className="px-2 py-0.5 rounded-full bg-[#EFF6FF] text-[#3B82F6] font-medium">
            {draft.category}
          </span>
          {draft.signal_type && (
            <span className="font-mono text-[#94a3b8]">· {draft.signal_type}</span>
          )}
          <span>
            ·{" "}
            {tab === "approved" && draft.published_at
              ? `published ${timeAgo(draft.published_at)}`
              : timeAgo(draft.created_at)}
          </span>
        </div>
        <h3 className="text-xl font-bold text-[#0F1D2E] leading-tight">
          {draft.title}
        </h3>
        {draft.excerpt && (
          <p className="text-sm text-[#334155] mt-2">{draft.excerpt}</p>
        )}
        {draft.body && (
          <details className="mt-3">
            <summary className="text-sm text-[#3B82F6] cursor-pointer select-none">
              View body
            </summary>
            <pre className="whitespace-pre-wrap text-sm leading-relaxed text-[#0F1D2E] mt-3 p-4 bg-[#f8fafc] rounded-lg font-sans">
              {draft.body}
            </pre>
          </details>
        )}
        {draft.signal_metadata && (
          <details className="mt-2">
            <summary className="text-xs text-[#64748b] cursor-pointer select-none">
              Signal data
            </summary>
            <pre className="text-xs font-mono text-[#334155] mt-2 p-3 bg-[#f8fafc] rounded overflow-x-auto">
              {JSON.stringify(draft.signal_metadata, null, 2)}
            </pre>
          </details>
        )}
      </div>
      {tab === "pending" && (
        <div className="flex items-center justify-end gap-2 px-5 py-3 bg-[#f8fafc] border-t border-[#e2e8f0]">
          <form action={reject}>
            <button
              type="submit"
              className="text-sm font-medium text-[#EF4444] hover:bg-red-50 px-4 py-2 rounded-lg transition"
            >
              Reject
            </button>
          </form>
          <form action={approve}>
            <button
              type="submit"
              className="text-sm font-semibold text-white bg-[#3B82F6] hover:bg-[#2563EB] px-5 py-2 rounded-lg transition"
            >
              Approve &amp; publish
            </button>
          </form>
        </div>
      )}
    </article>
  );
}
