-- Partition complaints_311 by metro for faster queries.
-- Applied manually on 2026-04-07. This file documents the schema change.
--
-- Before: single 23M-row / 13GB table, every query scanned all metros
-- After: 5 partitions, queries only scan the relevant metro's partition
--
-- Partition sizes:
--   chicago:     13.5M rows
--   nyc:          3.6M rows
--   los-angeles:  3.5M rows
--   miami:        1.7M rows
--   houston:      0.9M rows

-- NOTE: This migration was applied directly to production.
-- The table was created as complaints_311_part, data copied per-metro,
-- then swapped via ALTER TABLE RENAME.

-- Schema (already applied):
-- CREATE TABLE complaints_311 (
--   id uuid NOT NULL DEFAULT gen_random_uuid(),
--   building_id uuid,
--   unique_key text,
--   complaint_type text,
--   descriptor text,
--   agency text,
--   status text,
--   created_date timestamptz,
--   closed_date timestamptz,
--   resolution_description text,
--   borough text,
--   incident_address text,
--   latitude numeric,
--   longitude numeric,
--   imported_at timestamptz,
--   metro text NOT NULL,
--   zip_code text,
--   parsed_house_num text,
--   parsed_street text,
--   PRIMARY KEY (id, metro)
-- ) PARTITION BY LIST (metro);
--
-- CREATE TABLE complaints_311_nyc PARTITION OF complaints_311 FOR VALUES IN ('nyc');
-- CREATE TABLE complaints_311_chicago PARTITION OF complaints_311 FOR VALUES IN ('chicago');
-- CREATE TABLE complaints_311_la PARTITION OF complaints_311 FOR VALUES IN ('los-angeles');
-- CREATE TABLE complaints_311_miami PARTITION OF complaints_311 FOR VALUES IN ('miami');
-- CREATE TABLE complaints_311_houston PARTITION OF complaints_311 FOR VALUES IN ('houston');
--
-- CREATE UNIQUE INDEX complaints_311_part_unique_key ON complaints_311 (unique_key, metro);
-- CREATE INDEX complaints_311_part_building_id ON complaints_311 (building_id);
-- CREATE INDEX complaints_311_part_metro ON complaints_311 (metro);
-- CREATE INDEX complaints_311_part_created_date ON complaints_311 (created_date DESC);
--
-- ALTER TABLE complaints_311 ADD CONSTRAINT complaints_311_building_id_fkey
--   FOREIGN KEY (building_id) REFERENCES buildings(id) ON DELETE SET NULL;
